### ISSUE TITLE
Deprecated code.

### ISSUE THREAD

**Issue by 23Chromosomes** [ditdot-dev/dark-mode-example#3]
// Listen for changes in the OS settings
useDark.addListener(function(evt) {
toggleDarkMode(evt.matches);
});

Should use addEventListener to future proof the code.

**Comment by spinn** [comment]
@23Chromosomes Thanks for the suggestion. The reason we used the deprecated version is because older versions of Safari (both on iOS and macOS) don't support addEventListener. Newer versions do though, but to be properly backwards-compatible the best approach would be to check if addEventListener exists on MediaQueryList and use the one that exists.
